### ISSUE TITLE
Lack of type 0x92

### ISSUE THREAD

**Issue by FinBird** [oobol2000oo/RETON#1]

**Comment by FinBird** [comment]
Good job! But it seems that your rton-json convertor miss the type 0x92,93.Means Utf-8 code points,similar to 0x90,91
0X92+Varint+? String cache (key&value)(UTF-8)
0X93+Varint+? Referred String (key&value)(UTF-8)

**Comment by h3x4n1um** [comment]
Thank you, I'll implement it asap

**Comment by h3x4n1um** [comment]
> Good job! But it seems that your rton-json convertor miss the type 0x92,93.Means Utf-8 code points,similar to 0x90,91
> 0X92+Varint+? String cache (key&value)(UTF-8)
> 0X93+Varint+? Referred String (key&value)(UTF-8)

Could you give me an example, please?

**Comment by FinBird** [comment]
@h3x4n1um Get it 
[https://file.io/Kudyhy](url)

**Comment by FinBird** [comment]
May be participate in the project later in this year...

**Comment by FinBird** [comment]
Also, could you leave your mail? :-)

**Comment by h3x4n1um** [comment]
Contact me at fb.com/nthoanghai

**Comment by h3x4n1um** [comment]
> @h3x4n1um Get it
> [https://file.io/Kudyhy](url)

I examined your file sent to me ~and I found that your file missing the `0x93` bytecode.~

I implemented the `0x92` and `0x93`, ~`0x92`~ **it** works like a charm ~but I not sure `0x93` translates properly~
