### ISSUE TITLE
Error: vector::_M_range_check: __n (which is 112414) >= this->size() (which is 112414)

### ISSUE THREAD

**Issue by panyushkin** [oobol2000oo/RETON#11]
Greetings. Thank you for your work.
I've been playing PvZ2 for a long time. The pp.dat file has grown to over 112 Kb. When trying to convert it, the following message is displayed:

```
Processing file "pp.dat" - RTON Detected
vector::_M_range_check: __n (which is 112414) >= this->size() (which is 112414)
Completed in 0.873305s

Finished
```

It is written that it is completed, but an error code is displayed and the file is not created.

**Comment by h3x4n1um** [comment]
Can you upload your pp.dat file for me to investigate?

**Comment by panyushkin** [comment]
Uploaded here:
https://github.com/panyushkin/zipper

**Comment by h3x4n1um** [comment]
Your pp.dat is corrupted
![image](https://user-images.githubusercontent.com/8504326/106995492-f0483d00-6776-11eb-88eb-7874bac66d14.png)
