### ISSUE TITLE
Empty dictionaries are listed as "null"

### ISSUE THREAD

**Issue by bontchev** [oobol2000oo/RETON#13]
If the original JSON file that was compressed to RTON contained keys the value of which was an empty dictionary, `rton2json` outputs `null` instead of `[]`.

Like, if the original was

```
{
    ...
    "objdata": {}
    ....
}
```

`rton2json` would convert it to

```
{
    ...
    "objdata": null
    ....
}
```

This is probably a bug.

**Comment by h3x4n1um** [comment]
Thankyou for your bug report

Interesting, ~I think this might be a bug of json library, let's me check on the library ASAP~

It's rton2json bug, I should have initiated

```cpp
json_fifo::json res = json_fifo::json::object(),
```

Instead of

https://github.com/h3x4n1um/RETON/blob/8d295f30f65e06262a4d8e8d7f079dd294e488bf/rton-json/src/rton2json.cpp#L290

**Comment by bontchev** [comment]
Ah, any chance of making a release with the fix? I don't have a C++ compiler, so I can't compile it myself. I tried rewriting the thing in Python, but my C++ is sketchy and there are many things I don't understand.

**Comment by h3x4n1um** [comment]
> 
> 
> Ah, any chance of making a release with the fix? I don't have a C++ compiler, so I can't compile it myself. I tried rewriting the thing in Python, but my C++ is sketchy and there are many things I don't understand.

I just release 3.1.1
