### ISSUE TITLE
Some files cannot be unpacked correctly

### ISSUE THREAD

**Issue by bontchev** [oobol2000oo/RETON#15]
When trying to unpack [this file](https://ufile.io/o6cjd4pg), the program `rton2json` produces the following error:

```
Error reading chunk type 0x0 at 0x2f6!!!
```

**Comment by h3x4n1um** [comment]
I take a look into your file, I think maybe it's typo in `0x2f5` that it should be `0x81`

If `0x83` then follows it (`0x2f6`) must be `0x2` or `0x3`

So it can't be `0x83` (except this is an edge case that I haven't seen before)

But after `0x2f5`, `0x2f6` is an `0x0` (probably size of some thing) so I assume it likely a typos of `0x81`

**Comment by bontchev** [comment]
I'm not sure I understand what you are saying but this file is from the game; it is created by it. If it was the game that put the wrong value there, it wouldn't be able to use this file.

**Comment by nineteendo** [comment]
This is another subtype from 0x83: 0x0 which probably translates to RTID():
[save_LevelModuleInstances.zip](https://github.com/h3x4n1um/RETON/files/6608776/save_LevelModuleInstances.zip)
I have converted the file using my python equivalent of your tool so you can see how this would look like: https://github.com/Nineteendo/PVZ2tools/tree/master/RTONS_PARSER, I'm not sure if this might be useful for you.
