### ISSUE TITLE
Feature request: Implement non-interactive use

### ISSUE THREAD

**Issue by bontchev** [oobol2000oo/RETON#16]
Currently, when the program `rton2json` is instructed to unpack a subdirectory, after it is done, it displays the message `Finished` and waits for the user to press Enter. I often unpack the RTON files of a whole subtree of directories and the program constantly waiting for me to press Enter is rather annoying. Could you please implement a command-line option that suppresses this pause?

**Comment by h3x4n1um** [comment]
This shouldn't be hard to implement but currently I have a lot of university projects, I'll take look at this when I have more free time
