### ISSUE TITLE
Error reading bytecode 0x13 at 0x283f

### ISSUE THREAD

**Issue by NM-20** [oobol2000oo/RETON#2]
After inputting the path to a pp.dat, an error is returned with the message "ERROR READING BYTECODE 0x13 AT 0x283f!!!"

![unknown](https://user-images.githubusercontent.com/35472796/58852790-e4cd7600-8665-11e9-9583-b7e420155d35.png)

**Comment by h3x4n1um** [comment]
Could you upload your pp.dat file please?

**Comment by FinBird** [comment]
A good but no complete RTON index can be found here: [https://plantsvszombies.fandom.com/wiki/User_blog:1Zulu/RTON_Format](url) 
May be helpful to reduce type missing

**Comment by h3x4n1um** [comment]
Thankyou so much @FinBird 

I'll implement missing bytecode on that cheatsheet asap

**Comment by NM-20** [comment]
Here is the pp.dat that returns the error. I had to zip it due to github not supporting the file type.
[pp.dat.zip](https://github.com/h3x4n1um/RETON/files/3258101/pp.dat.zip)

**Comment by h3x4n1um** [comment]
Fixed in 2.4.0, thanks for your help @NM-20
