### ISSUE TITLE
About rton>json>rton

### ISSUE THREAD

**Issue by Dhyfer1** [oobol2000oo/RETON#4]
Hi. I need your help, I'm not an advanced user neither much less a developer. I know that RTON is a PopCap owner file, creator of the saga Plants vs Zombies, and as a game fan I would also like to make reverse engineering to PvZ.

On Android, the game creates many RTON files in your installation directory, and what I want is to edit some RTON files converted first to JSON files, (because as a json file is easier to edit) and after editing the JSON file, reconvert it in a RTON file.

So in Github the only reference that I found about RTON is your project and I have downloaded it, but I don't know how to use your RTON-JSON/JSON-RTON converter and there is not executable file inside the ZIP file that can help me with what I need.

So, please, you can tell me how your project is used for what I need? Remember that I'm not an advanced user.

I wait for your answer.

**Comment by FinBird** [comment]
Hello,from your statement,I think you are willing to understand and get some RTON file?
From your words,​ you are in search of some.rton?
In fact,all the files in Android/data/com.ea.pvz2_row/files/No_Backup or Android/data/com.ea.pvz2_na/files/No_Backup are RTON file.Meanwhile,you can extract more .rton in.obb in Android/obb/com.ea.pvz2_row 
​For more,I reference thefollowing links(a little out of date),which providesmore information of RTON and more about pvz2 's obb(the resource of the game)
Hope it will be helpful to you.
https://plantsvszombies.fandom.com/wiki/User_blog:1Zulu/RTON_Format​
https://plantsvszombies.fandom.com/wiki/User_blog:1Zulu/Inner_workings
​(Some json reversed from rton:https://github.com/FinBird/P2-ObbUtil)

**Comment by h3x4n1um** [comment]
Closed because this is not bug either or error with my tool

And also thanks @FinBird for pointing that out for him

**Comment by h3x4n1um** [comment]
If you need a executable please check release section here:

https://github.com/h3x4n1um/RETON/releases
