### ISSUE TITLE
Error reading pp.dat

### ISSUE THREAD

**Issue by Dhyfer1** [oobol2000oo/RETON#5]
![error code 2](https://user-images.githubusercontent.com/50301201/64374799-26b1e380-cfea-11e9-943e-e08fa7466ca4.png)
Hi H3x4n1um. 

In version 7.5.1 of PVZ2, I could use your rton-json tool without problem in the pp.dat file. 

Yesterday was filtered the latest version of the game (7.6.1), but now rton-json does not work with the pp.dat file of the new version; when I want that rton-json to work with the pp.dat file, the following message appears:

Error reading bytecode 0x46 at 0x9a!!!
Error code: 2

As I said before, there was no problem with rton-json in the conversion of the pp.dat file of the previous version of the game, but now rton-json can not read the pp.dat file from the new version.

So, so you can check that error message, attach my pp.dat file and I must clarify that I use the latest version 2.7.2 of rton-json.

What causes that error message? There is some solution?

I hope your answer. 
[File pp dat.zip](https://github.com/h3x4n1um/RETON/files/3580856/File.pp.dat.zip)

**Comment by h3x4n1um** [comment]
Thanks for reporting bug, I'll look into it asap

**Comment by TileTurnip** [comment]
0x46 → UInt64
0x40 → Int64
0x47 → 0
Here are some suggestions if needed

**Comment by h3x4n1um** [comment]
Try [this version](https://1drv.ms/u/s!AnAKocoSOJ0Vip08r7eKjBSRShRvRg?e=Wrd616) I just built and report the result, thanks

**Comment by Dhyfer1** [comment]
Hi H3x4n1um. 

First that all, thank you for attending my issue.

Well, I have downloaded the updated version (2.7.3) of rton-json but can not yet work with the pp.dat file of the latest version of the game, and now shows the error message that you can see in the next image:

![Error reading pp](https://user-images.githubusercontent.com/50301201/64491651-ad580200-d230-11e9-9be1-c5b89e6ddac1.png)

I thank you for taking your time to update your program, now I hope that the next version of rton-json can work without problem and for you to verify the error code showed and prevent new error messages also attach my new pp.dat file.

[new pp.dat.zip](https://github.com/h3x4n1um/RETON/files/3587814/new.pp.dat.zip)

That's all for now. I will be pending your answer.

Regards. 

P. S. You have some plan to bring rton-json as an app for Android? For me it would be of great utility.

**Comment by Dhyfer1** [comment]
> Try [this version](https://1drv.ms/u/s!AnAKocoSOJ0Vip08r7eKjBSRShRvRg?e=Wrd616) I just built and report the result, thanks

Hi H3x4n1um. 

First that all, thank you for attending my issue.

Well, I have downloaded the updated version (2.7.3) of rton-json but can not yet work with the pp.dat file of the latest version of the game, and now shows the error message that you can see in the next image:

![Error reading pp](https://user-images.githubusercontent.com/50301201/64491651-ad580200-d230-11e9-9be1-c5b89e6ddac1.png)

I thank you for taking your time to update your program, now I hope that the next version of rton-json can work without problem and for you to verify the error code showed and prevent new error messages also attach my new pp.dat file.

[new pp.dat.zip](https://github.com/h3x4n1um/RETON/files/3587814/new.pp.dat.zip)

That's all for now. I will be pending your answer.

Regards. 

P. S. You have some plan to bring rton-json as an app for Android? For me it would be of great utility.

**Comment by h3x4n1um** [comment]
~~I'm pretty busy right now, might investigate after few weeks~~

Download new build (link doesn't change) and try again

**Comment by Dhyfer1** [comment]
Hi H3x4n1um 

I have returned to download rton-json and I can confirm that now it works without problem so much in the conversion to .json file and back to file .rton with the updated pp.dat file. Do not attach image because I didn't think it necessary when I to see that the last build works without problem.

Again, I thank you for taking your time to re-correct the error presented and we hope that the next update of the game does not change the pp.dat file again.

Now that you know that the new rton-json build works, you can upload it to the release section with total security.

That is all for now. Thank you very much for attending and solving my issue.

P. S. Some things I would like to see in the future of rton-json are the following:
- Conversion of more than one rton/json file at once
- Unpack and pack the .obb file
- rton-json as an App for Android or at least be an online tool.

**Comment by h3x4n1um** [comment]
> Again, I thank you for taking your time to re-correct the error presented and we hope that the next update of the game does not change the pp.dat file again.

The game doesn't change anything in this scenarios, I just missing few bytecodes in RTON :P and new update uses it so my tool doesn't work

**Comment by arzer0ne** [comment]
> Try [this version](https://1drv.ms/u/s!AnAKocoSOJ0Vip08r7eKjBSRShRvRg?e=Wrd616) I just built and report the result, thanks

Is this link still working? I'm having the same issue and I think I should give it a try.

**Comment by h3x4n1um** [comment]
> 
> 
> > Try [this version](https://1drv.ms/u/s!AnAKocoSOJ0Vip08r7eKjBSRShRvRg?e=Wrd616) I just built and report the result, thanks
> 
> Is this link still working? I'm having the same issue and I think I should give it a try.

What problem you have?
