### ISSUE TITLE
Another Error Reading pp.dat

### ISSUE THREAD

**Issue by Atto10A** [oobol2000oo/RETON#8]
Hello h3x4n1um,

I'm using your program to convert pp.dat from PvZ2 7.81 to a json file and get the following error 
<a href='https://postimages.org/' target='_blank'><img src='https://i.postimg.cc/Ls4RP8sr/Schermopname-13.png' border='0' alt='Schermopname-13'/></a>
Error reading bytecode 0x16 at 0xfffffffffffffffe!!!
Error code: 2

I hope you know how to fix this error

Sincerely Yours, Atto.

I've also attached the pp.dat file.
[pp.zip](https://github.com/h3x4n1um/RETON/files/4041415/pp.zip)

**Comment by h3x4n1um** [comment]
Thankyou, I'll look into this asap

**Comment by h3x4n1um** [comment]
Your pp.dat is corrupted, try to copy it again from where you obtain it

**Comment by nineteendo** [comment]
This is actually yet another file without the DONE marker, you should actually allow to edit this by catching the error and interpreting this as a ArrayEnd or as a ObjectEnd until you closed the first object. If you would do that this is the output:
[pp.json.zip](https://github.com/h3x4n1um/RETON/files/6610811/pp.json.zip)
